name: SITL Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-simulation-bionic:2020-01-13
    steps:
    # see https://github.com/actions/checkout/issues/14
    - uses: actions/checkout@v1
    - name: disable the keychain credential helper
      run: git config --global credential.helper ""
    - name: enable the local store credential helper
      run: git config --global --add credential.helper store
    - name: add credential
      run: echo "https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com" >> ~/.git-credentials
    - name: tell git to use https instead of ssh whenever it encounters it
      run: 'git config --global url."https://github.com/".insteadof git@github.com:'
    - name: get submodules
      run: 'git submodule update --init --recursive'
    - name: Download MAVSDK
      run: wget https://github.com/mavlink/MAVSDK/releases/download/v0.23.0/mavsdk_0.23.0_ubuntu18.04_amd64.deb
    - name: Install MAVSDK
      run: dpkg -i mavsdk_0.23.0_ubuntu18.04_amd64.deb
    - name: Install psutil
      run: pip3 install psutil
    - name: Build PX4 in SITL integration test mode
      # Build all targets
      run: DONT_RUN=1 make px4_sitl gazebo mavsdk_tests
    - name: Run simulation tests
      # Grind configuration: Change iterations to a number between 20 and 100 (30 minutes to about 3 hours runtime)
      run:  test/mavsdk_tests/mavsdk_test_runner.py --speed-factor 20 --iterations 1 --fail-early
